title: NetDevOps
author: Nick Moore
email: nick.moore@pm.me
description: > # this means to ignore newlines until "baseurl:"
  Interests include family, traveling, crypto-currency, baseball, Infrastructure As Code startups, & all things technology.

# social links
twitter_username: @holynakamoto
github_username:  holynakamoto

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
